version: '3'
services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=wherewego
      - POSTGRES_PASSWORD=wherewego
      - POSTGRES_DB=wherewego
    volumes:
      - postgres-17-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wherewego -d wherewego"]
      interval: 5s
      timeout: 2s
      retries: 10

volumes:
  postgres-17-data:

networks:
  default:
    driver: bridge
